//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemAnswer
    {
        public int ProblemAnswerID { get; set; }
        public int ProblemID { get; set; }
        public int StudentID { get; set; }
        public string Answer { get; set; }
        public int Attempt { get; set; }
        public Nullable<int> TutorID { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
