//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Template
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProblemSolution
    {
        public int ProblemSolutionID { get; set; }
        public int ProblemID { get; set; }
        public string Solution { get; set; }
    }
}
